---
name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.13.x", "1.14.x", "1.15.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: License check
        run: ./scripts/licensecheck.sh

      - name: Go installation
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Go dependencies installation
        run: go get -d ./...

      - name: Golint installation
        run: go get -u golang.org/x/lint/golint

      - name: Build
        run: go build ./...

      - name: Lint
        run: ./scripts/golint.sh

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
